DEFAULT_SETTINGS = {
    "key": "site",
    "contactEmail": "",
    "ownerNotifyEmail": "",
    "github": "",
    "linkedin": "",
    "available": True,
    "location": "Philippines",
    "siteName": "AMURAO.DEV",
    "version": "PORTFOLIO / 1.0",
}

DEFAULT_SERVICES = [
    {
        "id": "fullstack", "num": "01", "title": "FULL-STACK WEB DEVELOPMENT",
        "blurb": "Complete web systems — interface, server, database — built as one coherent product.",
        "order": 1,
        "capabilities": [
            {"name": "Custom Website Development", "desc": "Responsive websites developed around business requirements.", "status": "AVAILABLE"},
            {"name": "Web Application Development", "desc": "Interactive database-driven applications.", "status": "CORE"},
            {"name": "Frontend Development", "desc": "Modern responsive interfaces and application UI.", "status": "CORE"},
            {"name": "Backend Development", "desc": "Server-side business logic, authentication, workflows, and APIs.", "status": "CORE"},
            {"name": "Laravel Development", "desc": "Custom Laravel-based systems and applications.", "status": "CORE"},
            {"name": "Vue.js Development", "desc": "Interactive Vue-based frontend applications.", "status": "CORE"},
            {"name": "React / JavaScript Development", "desc": "Component-based modern frontend development.", "status": "AVAILABLE"},
            {"name": "Website Redesign", "desc": "Modernization of outdated interfaces and codebases.", "status": "AVAILABLE"},
            {"name": "Responsive Development", "desc": "Optimization across desktop, tablet, and mobile devices.", "status": "AVAILABLE"},
            {"name": "Existing System Improvements", "desc": "Adding functionality or repairing incomplete systems.", "status": "AVAILABLE"},
        ],
    },
    {
        "id": "uiux", "num": "02", "title": "UI/UX & PRODUCT DESIGN",
        "blurb": "Interfaces planned around real user flows — not decoration.",
        "order": 2,
        "capabilities": [
            {"name": "Figma UI Design", "desc": "High-fidelity application and website interfaces.", "status": "CORE"},
            {"name": "UX Planning", "desc": "User flows, page architecture, interaction planning.", "status": "CORE"},
            {"name": "Wireframing", "desc": "Low-to-mid fidelity product structure.", "status": "AVAILABLE"},
            {"name": "Interactive Prototyping", "desc": "Clickable application prototypes.", "status": "AVAILABLE"},
            {"name": "Responsive Interface Design", "desc": "Desktop, tablet, and mobile interface planning.", "status": "AVAILABLE"},
            {"name": "Dashboard Design", "desc": "Administrative and analytics dashboards.", "status": "CORE"},
            {"name": "UI/UX Audit", "desc": "Identify usability, accessibility, responsiveness, and interaction issues.", "status": "AVAILABLE"},
            {"name": "Design System Creation", "desc": "Reusable typography, color, spacing, and components.", "status": "AVAILABLE"},
        ],
    },
    {
        "id": "ecommerce", "num": "03", "title": "E-COMMERCE DEVELOPMENT",
        "blurb": "Storefronts with real commerce logic underneath — cart, checkout, orders, inventory, payments.",
        "order": 3,
        "capabilities": [
            {"name": "Custom E-Commerce Systems", "desc": "Complete commerce platforms built around your catalog and workflow.", "status": "CORE"},
            {"name": "Product Management", "desc": "Catalog, variants, pricing, and media administration.", "status": "CORE"},
            {"name": "Shopping Cart Development", "desc": "Persistent, validated cart flows.", "status": "CORE"},
            {"name": "Checkout Development", "desc": "Structured, reliable checkout pipelines.", "status": "CORE"},
            {"name": "Customer Authentication", "desc": "Accounts, sessions, and customer profiles.", "status": "CORE"},
            {"name": "Order Management", "desc": "Order state, history, and fulfillment tracking.", "status": "CORE"},
            {"name": "Inventory Management", "desc": "Stock levels, adjustments, and alerts.", "status": "AVAILABLE"},
            {"name": "Admin Dashboard", "desc": "Operational control panels for the whole store.", "status": "CORE"},
            {"name": "Payment Gateway Integration", "desc": "HitPay, Stripe, PayPal, or WooCommerce — depending on project requirements.", "status": "AVAILABLE"},
        ],
    },
    {
        "id": "backend", "num": "04", "title": "BACKEND, API & DATABASE DEVELOPMENT",
        "blurb": "The part of the system nobody sees — until it breaks. Built so it doesn't.",
        "order": 4,
        "capabilities": [
            {"name": "REST API Development", "desc": "Structured, documented API endpoints.", "status": "CORE"},
            {"name": "Database Architecture", "desc": "Schema design around real data relationships.", "status": "CORE"},
            {"name": "MySQL Database Development", "desc": "Relational design, queries, and management.", "status": "CORE"},
            {"name": "Authentication Systems", "desc": "Secure login, sessions, and credential handling.", "status": "CORE"},
            {"name": "Role-Based Access Control", "desc": "Permissions mapped to actual organizational roles.", "status": "CORE"},
            {"name": "Admin Panel Development", "desc": "Operational back-offices for non-technical staff.", "status": "CORE"},
            {"name": "CRUD Systems", "desc": "Reliable record management at every level.", "status": "CORE"},
            {"name": "Workflow Automation", "desc": "Digitized approvals, routing, and status flows.", "status": "AVAILABLE"},
            {"name": "Reporting Systems", "desc": "Filtered, exportable operational reports.", "status": "AVAILABLE"},
            {"name": "Audit Logging", "desc": "Traceable record of system activity.", "status": "AVAILABLE"},
            {"name": "Existing Backend Integration", "desc": "Connecting new work into systems you already run.", "status": "AVAILABLE"},
        ],
    },
    {
        "id": "infosystems", "num": "05", "title": "BUSINESS & INFORMATION SYSTEMS",
        "blurb": "Internal systems built around how an organization actually operates.",
        "order": 5,
        "capabilities": [
            {"name": "Management Information Systems", "desc": "Decision-support systems for operations.", "status": "CORE"},
            {"name": "Laboratory Information Systems", "desc": "Sample tracking, results, and lab workflows.", "status": "EXPERIENCE"},
            {"name": "Operations Monitoring Systems", "desc": "Live visibility into ongoing operations.", "status": "EXPERIENCE"},
            {"name": "Internal Business Applications", "desc": "Tools shaped to internal processes.", "status": "CORE"},
            {"name": "Inventory Systems", "desc": "Stock, assets, and movement tracking.", "status": "AVAILABLE"},
            {"name": "Record Management", "desc": "Structured, searchable organizational records.", "status": "CORE"},
            {"name": "QR-Based Workflows", "desc": "Physical-to-digital tracking via QR codes.", "status": "EXPERIENCE"},
            {"name": "User Management", "desc": "Accounts, roles, and access lifecycle.", "status": "CORE"},
            {"name": "Reporting Dashboards", "desc": "Operational metrics at a glance.", "status": "CORE"},
            {"name": "Workflow Digitization", "desc": "Paper and spreadsheet processes rebuilt as software.", "status": "AVAILABLE"},
        ],
    },
    {
        "id": "wordpress", "num": "06", "title": "WORDPRESS & CMS DEVELOPMENT",
        "blurb": "Fast, maintainable CMS builds when a custom system is more than you need.",
        "order": 6,
        "capabilities": [
            {"name": "WordPress Websites", "desc": "Business and portfolio sites on WordPress.", "status": "EXPERIENCE"},
            {"name": "WooCommerce Stores", "desc": "WordPress-based commerce.", "status": "EXPERIENCE"},
            {"name": "Elementor Development", "desc": "Structured Elementor builds that stay maintainable.", "status": "EXPERIENCE"},
            {"name": "Theme Customization", "desc": "Adapting themes without breaking them.", "status": "AVAILABLE"},
            {"name": "Plugin Configuration", "desc": "Selecting and configuring the right plugins.", "status": "AVAILABLE"},
            {"name": "Responsive Optimization", "desc": "Making existing WordPress sites work on every device.", "status": "AVAILABLE"},
            {"name": "Website Maintenance", "desc": "Updates, backups, and small ongoing changes.", "status": "AVAILABLE"},
            {"name": "Existing WordPress Improvements", "desc": "Repairing and extending existing installs.", "status": "AVAILABLE"},
        ],
    },
    {
        "id": "support", "num": "07", "title": "DEVELOPMENT SUPPORT",
        "blurb": "For systems that already exist — fixing, extending, documenting, shipping.",
        "order": 7,
        "capabilities": [
            {"name": "Bug Fixing", "desc": "Diagnosis and repair of broken functionality.", "status": "AVAILABLE"},
            {"name": "Feature Development", "desc": "New functionality inside existing systems.", "status": "AVAILABLE"},
            {"name": "Frontend-to-Backend Integration", "desc": "Making separated halves of a system talk.", "status": "AVAILABLE"},
            {"name": "API Integration", "desc": "Third-party services wired into your workflows.", "status": "AVAILABLE"},
            {"name": "Database Troubleshooting", "desc": "Data, query, and schema issues resolved.", "status": "AVAILABLE"},
            {"name": "Deployment Assistance", "desc": "Getting systems live and configured.", "status": "AVAILABLE"},
            {"name": "System Testing", "desc": "Functional and regression testing passes.", "status": "AVAILABLE"},
            {"name": "UX Testing", "desc": "Real-flow usability review.", "status": "AVAILABLE"},
            {"name": "Documentation", "desc": "System documentation people actually read.", "status": "AVAILABLE"},
            {"name": "User Manuals", "desc": "End-user guides for staff and customers.", "status": "AVAILABLE"},
            {"name": "Technical Documentation", "desc": "Architecture, setup, and maintenance references.", "status": "AVAILABLE"},
            {"name": "Post-Deployment Support", "desc": "Support after launch, not disappearing after handover.", "status": "AVAILABLE"},
        ],
    },
]

DEFAULT_PRICING = [
    {
        "id": "landing", "name": "Landing Page / Basic Website", "model": "STARTING AT",
        "price": "₱8,000", "order": 1, "featured": False,
        "includes": ["Landing pages", "Personal websites", "Small business websites", "Informational websites"],
        "note": "Scope defined by page count, content, and interactivity.",
        "cta": "Discuss Project",
    },
    {
        "id": "business", "name": "Professional Business Website", "model": "STARTING AT",
        "price": "₱15,000", "order": 2, "featured": False,
        "includes": ["Multiple pages", "Responsive development", "Custom UI", "Contact forms", "Basic SEO", "Deployment assistance"],
        "note": "Content management and integrations adjust the estimate.",
        "cta": "Discuss Project",
    },
    {
        "id": "uiux", "name": "UI/UX Design", "model": "STARTING AT",
        "price": "₱5,000", "order": 3, "featured": False,
        "includes": ["Number of screens", "Research", "Wireframes", "Prototype complexity", "Responsive versions"],
        "note": "Priced per screen count and fidelity requirements.",
        "cta": "Discuss Design",
    },
    {
        "id": "ecommerce", "name": "E-Commerce", "model": "STARTING AT",
        "price": "₱25,000", "order": 4, "featured": True,
        "includes": ["Products", "Authentication", "Cart", "Checkout", "Customer accounts", "Order management"],
        "note": "Payment integrations and complex administration may increase pricing.",
        "cta": "Discuss Store",
    },
    {
        "id": "system", "name": "Custom Information System", "model": "STARTING AT",
        "price": "₱30,000+", "order": 5, "featured": True,
        "includes": ["Modules", "Roles", "Workflows", "Database complexity", "Integrations", "Reporting", "Deployment"],
        "note": "Scoped per module, role count, and workflow depth.",
        "cta": "Request System Estimate",
    },
    {
        "id": "support", "name": "Development / Bug Fixing", "model": "STARTING AT",
        "price": "₱1,500", "order": 6, "featured": False,
        "includes": ["Issue diagnosis", "Bug repair", "Small features", "Integration fixes"],
        "note": "Custom quotation based on the issue.",
        "cta": "Describe the Issue",
    },
]

DEFAULT_PROJECTS = [
    {
        "id": "p-studya", "slug": "studya", "num": "001", "title": "StudYA",
        "subtitle": "E-Commerce Platform", "year": "2026",
        "categories": ["FULL STACK", "E-COMMERCE"], "type": "Full-Stack Development",
        "role": "Full-Stack Developer", "disclosure": "PUBLIC", "featured": True, "order": 1,
        "stack": ["Laravel", "Vue.js", "Inertia.js", "MySQL", "HitPay"],
        "features": ["Authentication", "Shopping Cart", "Checkout", "Administration", "Payment Integration"],
        "description": "Full-stack e-commerce platform covering the complete purchase flow — from authentication and cart to checkout, administration, and integrated payments.",
        "architecture": ["USER", "VUE INTERFACE", "INERTIA", "LARAVEL", "BUSINESS LOGIC", "MYSQL", "PAYMENT / EXTERNAL APIS"],
        "caseStudy": {
            "overview": "StudYA is a full-stack e-commerce platform built with Laravel, Vue.js, Inertia.js, and MySQL. It handles the entire commerce lifecycle: customer authentication, product browsing, cart management, checkout, order administration, and payment processing through HitPay.",
            "problem": "The project required a complete commerce system — storefront, cart, checkout, administration, and payments — built as one coherent product rather than a collection of disconnected pages.",
            "role": "Sole full-stack developer: system planning, database design, backend development, frontend implementation, payment gateway integration, testing, and deployment.",
            "process": "Database schema first, then Laravel business logic, then the Inertia + Vue interface layer, then payment integration, then end-to-end testing of the full purchase flow.",
            "challenges": "Keeping order state consistent across checkout and asynchronous payment gateway callbacks inside a server-driven Inertia flow.",
            "solutions": "Server-side order state handling in Laravel, with payment confirmation verified through gateway callbacks before an order is activated.",
            "result": "An operational e-commerce system with authentication, cart, checkout, administration, and integrated payments.",
            "learned": "End-to-end ownership of a commerce system — from schema design to payment edge cases — teaches more than any isolated feature ever could.",
        },
    },
    {
        "id": "p-soiltrack", "slug": "soiltrack", "num": "002", "title": "SoilTrack",
        "subtitle": "Laboratory Information System", "year": "2026",
        "categories": ["FULL STACK", "INFORMATION SYSTEMS"], "type": "Information System",
        "role": "Full-Stack Developer", "disclosure": "LIMITED DISCLOSURE", "featured": True, "order": 2,
        "stack": ["Laravel", "MySQL", "Role-Based Access", "SMS Integration"],
        "features": ["Sample Tracking", "Laboratory Results Management", "SMS Logs", "Role-Based Dashboards", "Admin / Staff Workflows", "Database-Driven Operations"],
        "description": "Laboratory information system developed for Department of Agriculture-related operations — sample tracking, results management, SMS logs, and role-based dashboards.",
        "architecture": ["STAFF / ADMIN", "ROLE-BASED DASHBOARD", "APPLICATION LOGIC", "SAMPLE TRACKING", "RESULTS MANAGEMENT", "MYSQL", "SMS LOGS"],
        "caseStudy": {
            "overview": "SoilTrack is a laboratory information system developed for Department of Agriculture-related operations. It digitizes sample tracking, laboratory results management, SMS logging, and role-separated staff workflows.",
            "problem": "Laboratory operations depended on manual tracking of samples and results across multiple staff roles — slow, error-prone, and hard to audit.",
            "role": "Full-stack developer: requirements analysis, database design, backend workflows, role-based dashboards, and testing.",
            "process": "Mapped the laboratory workflow first, designed the schema around samples and results, then built role-separated dashboards for administrators and staff.",
            "challenges": "Translating a real laboratory workflow into role-based system states without losing operational detail.",
            "solutions": "Modeled samples and results as first-class records with status transitions, SMS logs, and role-scoped views.",
            "result": "A digitized laboratory workflow with role-separated dashboards, sample tracking, results management, and auditable records.",
            "learned": "Information systems succeed when the data model mirrors the actual workflow of the organization using it.",
        },
    },
    {
        "id": "p-camela", "slug": "camela", "num": "003", "title": "Camela",
        "subtitle": "E-Commerce Website", "year": "2026",
        "categories": ["FULL STACK", "E-COMMERCE"], "type": "Full-Stack Development",
        "role": "Full-Stack Developer", "disclosure": "LIMITED DISCLOSURE", "featured": True, "order": 3,
        "stack": ["Laravel", "MySQL", "REST APIs", "Stripe"],
        "features": ["Authentication", "Products", "Cart", "Checkout", "Orders", "Inventory", "Administration", "Payment Processing"],
        "description": "Full-stack e-commerce development — converting an incomplete AI-generated frontend into an operational Laravel system with Stripe payments.",
        "architecture": ["CUSTOMER", "STOREFRONT UI", "REST API", "LARAVEL", "ORDERS / INVENTORY", "MYSQL", "STRIPE"],
        "caseStudy": {
            "overview": "Camela is a full-stack e-commerce system built by converting an incomplete AI-generated frontend into a working Laravel application with MySQL, REST APIs, and Stripe payments.",
            "problem": "An AI-generated frontend existed, but there was no functioning backend, database, or business logic behind it — the interface promised a system that didn't exist.",
            "role": "Full-stack developer: audited the existing frontend, designed the missing system underneath it, and implemented everything from database to payment processing.",
            "process": "Audited the generated interface, designed the schema and API surface it implied, then built authentication, products, cart, checkout, orders, inventory, and administration in Laravel.",
            "challenges": "Reverse-engineering an incomplete, inconsistent frontend and designing a coherent system beneath it without starting over.",
            "solutions": "Rebuilt the application around Laravel + MySQL with a clean REST API layer and Stripe payment processing.",
            "result": "An incomplete prototype converted into a functioning e-commerce system with authentication, orders, inventory, administration, and payment processing.",
            "learned": "Generated code can sketch an interface, but systems thinking is what makes software actually work.",
        },
    },
    {
        "id": "p-iot-ops", "slug": "iot-operations-platform", "num": "004", "title": "IoT Operations Platform",
        "subtitle": "Operations Monitoring & Management", "year": "2026",
        "categories": ["FULL STACK", "INFORMATION SYSTEMS"], "type": "Web Platform",
        "role": "Full-Stack Developer", "disclosure": "PRIVATE / NDA", "featured": False, "order": 4,
        "stack": ["Role-Based Access", "QR Workflows", "Audit Logging", "Reporting"],
        "features": ["Role-Based Access", "Dashboards", "Record Management", "QR Workflows", "Validation", "Reporting", "Audit Logging", "Administration", "Database-Driven Workflows", "UI Improvements"],
        "description": "Web-based operational monitoring and management platform with role-based access, QR workflows, validation, reporting, and audit logging.",
        "architecture": ["FIELD USERS", "QR WORKFLOWS", "WEB DASHBOARD", "VALIDATION LAYER", "RECORDS / REPORTS", "DATABASE", "AUDIT LOG"],
        "caseStudy": {
            "overview": "A web-based operational monitoring and management platform featuring role-based access, operational dashboards, record management, QR-based workflows, validation, reporting, audit logging, and administration. Details are limited by confidentiality; this entry presents capabilities rather than internals.",
            "problem": "Field operations needed digitized tracking, validation, and reporting with clear accountability.",
            "role": "Full-stack developer across workflows, dashboards, database operations, and UI improvements.",
            "process": "",
            "challenges": "",
            "solutions": "",
            "result": "",
            "learned": "",
        },
    },
    {
        "id": "p-cv-site", "slug": "professional-cv-website", "num": "005", "title": "Professional CV Website",
        "subtitle": "WordPress Portfolio", "year": "2024",
        "categories": ["WORDPRESS", "UI / UX"], "type": "WordPress Development",
        "role": "Developer / Designer", "disclosure": "PUBLIC", "featured": False, "order": 5,
        "stack": ["WordPress", "Elementor", "Responsive Design"],
        "features": ["Responsive Layout", "Elementor Build", "Portfolio Structure", "Contact Section"],
        "description": "Responsive portfolio and CV website built with WordPress and Elementor — an earlier project marking the start of client-facing development work.",
        "architecture": ["VISITOR", "WORDPRESS", "ELEMENTOR PAGES", "CONTENT", "HOSTING"],
        "caseStudy": {
            "overview": "A responsive portfolio / CV website built with WordPress and Elementor. An early project that established fundamentals: layout, responsiveness, content structure, and delivering for a real audience.",
            "problem": "",
            "role": "Developer and designer — structure, build, and responsive optimization.",
            "process": "",
            "challenges": "",
            "solutions": "",
            "result": "",
            "learned": "Where the journey started — before Laravel systems and e-commerce platforms, there was a WordPress build that had to simply work.",
        },
    },
]
