from io import BytesIO
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib.colors import HexColor
from reportlab.lib.utils import ImageReader
from reportlab.pdfgen import canvas
from db import db
from storage import put_object, get_object

GENERATED_PATH = "resumes/generated.pdf"
CUSTOM_PATH = "resumes/custom.pdf"

INK = HexColor("#15132E")
MUTED = HexColor("#5F6880")
VIOLET = HexColor("#6D28D9")
LINE = HexColor("#D8DDE6")

def _wrap(text, width):
    words, lines, cur = text.split(), [], ""
    for w in words:
        if len(cur) + len(w) + 1 <= width:
            cur = f"{cur} {w}".strip()
        else:
            lines.append(cur)
            cur = w
    if cur:
        lines.append(cur)
    return lines


def build_resume_bytes(data: dict, portrait_bytes: bytes | None = None) -> bytes:
    buf = BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    W, H = A4
    x, y = 18 * mm, H - 18 * mm

    def line(dy, size=9, font="Helvetica", color=INK, text=""):
        nonlocal y
        c.setFont(font, size)
        c.setFillColor(color)
        c.drawString(x, y, text)
        y -= dy

    def heading(text):
        nonlocal y
        y -= 3 * mm
        c.setStrokeColor(LINE)
        c.setLineWidth(0.5)
        c.line(x, y, W - 18 * mm, y)
        y -= 5 * mm
        c.setFont("Courier-Bold", 8)
        c.setFillColor(VIOLET)
        c.drawString(x, y, text.upper())
        y -= 4.5 * mm

    # optional portrait, top-right
    if portrait_bytes:
        try:
            ps = 26 * mm
            px, py = W - 18 * mm - ps, H - 18 * mm - ps + 4 * mm
            c.saveState()
            c.setStrokeColor(LINE)
            c.setLineWidth(0.7)
            c.rect(px, py, ps, ps, stroke=1, fill=0)
            c.drawImage(ImageReader(BytesIO(portrait_bytes)), px, py, ps, ps,
                        preserveAspectRatio=True, anchor="c", mask="auto")
            c.restoreState()
        except Exception:
            pass

    c.setFont("Courier", 7.5)
    c.setFillColor(VIOLET)
    c.drawString(x, y, "RESUME / CV — AMURAO.DEV")
    y -= 7 * mm
    line(7 * mm, 17, "Helvetica-Bold", INK, data["name"].upper())
    line(5 * mm, 8.5, "Helvetica", MUTED, data["title"])
    line(6 * mm, 8.5, "Courier", MUTED, f"LOCATION: {data['location'].upper()}")

    heading("Profile")
    for ln in _wrap(data["profile"], 100):
        line(4.2 * mm, 9, "Helvetica", INK, ln)

    heading("Education")
    for deg, school, yr in data["education"]:
        line(4.5 * mm, 9.5, "Helvetica-Bold", INK, deg)
        line(4 * mm, 8.5, "Helvetica", MUTED, f"{school}  ·  {yr}")

    heading("Experience")
    for role, yr, desc in data["experience"]:
        line(4.5 * mm, 9.5, "Helvetica-Bold", INK, role)
        line(3.8 * mm, 8, "Courier", VIOLET, yr)
        for ln in _wrap(desc, 105):
            line(4 * mm, 8.5, "Helvetica", MUTED, ln)
        y -= 1.5 * mm

    heading("Selected Projects")
    for title, desc, yr in data["projects"]:
        line(4.5 * mm, 9.5, "Helvetica-Bold", INK, f"{title}  ·  {yr}")
        for ln in _wrap(desc, 105):
            line(4 * mm, 8.5, "Helvetica", MUTED, ln)
        y -= 1 * mm

    heading("Technical Skills")
    for s in data["skills"]:
        line(4.2 * mm, 8.5, "Helvetica", INK, s)

    heading("Certifications")
    for name, org, yr in data["certifications"]:
        line(4.5 * mm, 9.5, "Helvetica-Bold", INK, name)
        line(4 * mm, 8.5, "Helvetica", MUTED, f"{org}  ·  {yr}")

    c.setFont("Courier", 7)
    c.setFillColor(MUTED)
    c.drawString(x, 12 * mm, "BUILD / SHIP / ITERATE — generated by amurao.dev, replaceable via admin panel")
    c.save()
    return buf.getvalue()


def _period(item: dict, start_key: str = "start", end_key: str = "end", current_key: str = "current") -> str:
    start = str(item.get(start_key, ""))
    if item.get(current_key):
        return f"{start} — Present"
    end = str(item.get(end_key, ""))
    return f"{start} — {end}" if end else start


async def get_resume_data() -> dict:
    """Build the website/PDF resume model exclusively from current MongoDB records."""
    singleton_docs = await db.singletons.find(
        {"key": {"$in": ["profile", "about", "contact"]}}, {"_id": 0}
    ).to_list(3)
    singletons = {doc["key"]: doc.get("data", {}) for doc in singleton_docs}
    profile = singletons.get("profile", {})
    about = singletons.get("about", {})

    query = {"status": "published", "archived": {"$ne": True}}
    experience = await db.experience.find(query, {"_id": 0}).sort("order", 1).to_list(100)
    education = await db.education.find(query, {"_id": 0}).sort("order", 1).to_list(100)
    projects = await db.projects.find(query, {"_id": 0}).sort("order", 1).to_list(100)
    skills = await db.skills.find(query, {"_id": 0}).sort("order", 1).to_list(100)
    certifications = await db.certifications.find(query, {"_id": 0}).sort("order", 1).to_list(100)

    return {
        "name": profile.get("fullName", ""),
        "title": profile.get("resumeTitle") or profile.get("title", ""),
        "location": profile.get("location", ""),
        "profile": profile.get("resumeSummary") or profile.get("shortBio") or about.get("shortBio", ""),
        "education": [
            (
                item.get("program") or item.get("degree", ""),
                item.get("institution", ""),
                _period(item, "startYear", "endYear", "currentEnrolled"),
            )
            for item in education
        ],
        "experience": [
            (
                f"{item.get('role', '')} — {item.get('org', '')}",
                _period(item),
                item.get("description") or " ".join(item.get("points") or []),
            )
            for item in experience
        ],
        "projects": [
            (
                " — ".join(filter(None, [item.get("title", ""), item.get("subtitle", "")])),
                " · ".join(item.get("stack") or []) + ((". " + item.get("description", "")) if item.get("description") else ""),
                str(item.get("year", "")),
            )
            for item in projects
        ],
        "skills": [
            f"{item.get('title', '').title()}: " + ", ".join(skill.get("name", "") for skill in item.get("items") or [])
            for item in skills if item.get("title") != "PROFESSIONAL SKILLS"
        ],
        "certifications": [
            (item.get("name", ""), item.get("issuer", ""), item.get("date", ""))
            for item in certifications
        ],
    }


async def get_portrait_bytes() -> bytes | None:
    prof = await db.about_profiles.find_one({"status": "published"}, {"_id": 0, "photos": 1})
    if not prof:
        return None
    photos = prof.get("photos") or []
    port = next((ph for ph in photos if ph.get("role") == "Professional Portrait" and ph.get("url")), None)
    if not port:
        return None
    media_id = port["url"].rstrip("/").split("/")[-1]
    media = await db.media.find_one({"id": media_id, "is_deleted": {"$ne": True}}, {"_id": 0})
    if not media:
        return None
    if media.get("content") is not None:
        return bytes(media["content"])
    try:
        storage_path = media.get("storage_path")
        if not storage_path:
            return None
        data, _ = await get_object(storage_path)
        return data
    except Exception:
        return None


async def ensure_generated_resume():
    existing = await db.files.find_one({"kind": "resume_generated", "is_deleted": False})
    if existing:
        try:
            await get_object(existing["storage_path"])
            return
        except FileNotFoundError:
            pass
    portrait = await get_portrait_bytes()
    resume_data = await get_resume_data()
    pdf = build_resume_bytes(resume_data, portrait)
    result = await put_object(GENERATED_PATH, pdf, "application/pdf")
    await db.files.update_one(
        {"kind": "resume_generated"},
        {"$set": {"kind": "resume_generated", "storage_path": result["path"], "is_deleted": False,
                  "size": result["size"], "content_type": "application/pdf"}},
        upsert=True,
    )


async def get_resume_bytes() -> bytes:
    custom = await db.files.find_one({"kind": "resume_custom", "is_deleted": False})
    if custom:
        try:
            data, _ = await get_object(custom["storage_path"])
            return data
        except FileNotFoundError:
            await db.files.update_one({"kind": "resume_custom"}, {"$set": {"is_deleted": True}})
    # regenerate fresh so the CV always reflects the current portrait
    portrait = await get_portrait_bytes()
    resume_data = await get_resume_data()
    return build_resume_bytes(resume_data, portrait)


async def save_custom_resume(content: bytes, filename: str) -> dict:
    result = await put_object(CUSTOM_PATH, content, "application/pdf")
    doc = {"kind": "resume_custom", "storage_path": result["path"], "is_deleted": False,
           "size": result["size"], "filename": filename, "content_type": "application/pdf"}
    await db.files.update_one({"kind": "resume_custom"}, {"$set": doc}, upsert=True)
    return doc
