// Schema-driven CMS registry: field definitions per collection/singleton.
// Field types: text, textarea, number, checkbox, select, list, pipelist, image, section

const STATUS_SELECT = { key: "status", label: "Status", type: "select", options: ["published", "draft", "hidden"] };
const ORDER_FIELD = { key: "order", label: "Display Order", type: "number" };

export const COLLECTION_SCHEMAS = {
  projects: {
    title: "PROJECTS", singular: "Project",
    search: ["title", "subtitle", "description", "type"],
    listSub: (i) => `${i.year || "—"} · ${i.type || "—"}`,
    preview: (i) => (i.slug ? `/work/${i.slug}` : null),
    defaults: {
      num: "", title: "", slug: "", subtitle: "", year: "2026", categories: [], type: "", role: "Full-Stack Developer",
      client: "", clientPrivate: false, disclosure: "PUBLIC", featured: false, stack: [], features: [],
      description: "", architecture: [], cover: "", screenshots: [], liveUrl: "", githubUrl: "",
      figmaUrl: "", videoUrl: "", status: "draft", order: 99,
      caseStudy: { overview: "", problem: "", requirements: "", role: "", uiux: "", process: "", challenges: "", solutions: "", outcome: "", learned: "" },
    },
    fields: [
      { type: "section", label: "BASIC INFORMATION" },
      { key: "num", label: "Project Number / ID", type: "text", required: true, hint: "e.g. 001" },
      { key: "title", label: "Project Name", type: "text", required: true },
      { key: "slug", label: "Slug (blank = auto)", type: "text" },
      { key: "subtitle", label: "Short Subtitle / Category", type: "text", required: true },
      { key: "description", label: "Short Description", type: "textarea", rows: 3, required: true },
      { key: "year", label: "Year", type: "text", required: true },
      { key: "type", label: "Project Type", type: "text", required: true },
      { key: "role", label: "My Role", type: "text", required: true },
      { key: "categories", label: "Categories", type: "list", hint: "FULL STACK, E-COMMERCE, INFORMATION SYSTEMS, UI / UX, WORDPRESS, EXPERIMENTS" },
      { type: "section", label: "VISIBILITY" },
      { key: "disclosure", label: "Disclosure Level", type: "select", options: ["PUBLIC", "LIMITED DISCLOSURE", "PRIVATE / NDA"] },
      { key: "client", label: "Client / Organization", type: "text" },
      { key: "clientPrivate", label: "Keep client name private", type: "checkbox" },
      { key: "featured", label: "Featured on homepage", type: "checkbox" },
      { type: "section", label: "TECHNOLOGIES & FEATURES" },
      { key: "stack", label: "Technology Stack", type: "list", required: true, hint: "e.g. Laravel, Vue.js, MySQL" },
      { key: "features", label: "Features / Capabilities", type: "list", required: true },
      { key: "architecture", label: "Architecture Diagram Nodes", type: "list", hint: "e.g. USER → VUE → LARAVEL → MYSQL" },
      { type: "section", label: "MEDIA & LINKS" },
      { key: "cover", label: "Cover Image", type: "image" },
      { key: "screenshots", label: "Project Screenshots — exactly 5 required to publish", type: "imagelist", exactLength: 5 },
      { key: "liveUrl", label: "Live Website URL (blank = hidden)", type: "text" },
      { key: "githubUrl", label: "GitHub URL (blank = hidden)", type: "text" },
      { key: "figmaUrl", label: "Figma URL (blank = hidden)", type: "text" },
      { key: "videoUrl", label: "Video / Demo URL (blank = hidden)", type: "text" },
      { type: "section", label: "CASE STUDY (blank sections are hidden publicly)" },
      { key: "caseStudy.overview", label: "01 Overview", type: "textarea", rows: 3 },
      { key: "caseStudy.problem", label: "02 Problem", type: "textarea", rows: 3 },
      { key: "caseStudy.requirements", label: "03 Requirements", type: "textarea", rows: 3 },
      { key: "caseStudy.role", label: "04 My Role", type: "textarea", rows: 3 },
      { key: "caseStudy.uiux", label: "08 UI/UX", type: "textarea", rows: 3 },
      { key: "caseStudy.process", label: "09 Development Process", type: "textarea", rows: 3 },
      { key: "caseStudy.challenges", label: "10 Challenges", type: "textarea", rows: 3 },
      { key: "caseStudy.solutions", label: "11 Solutions", type: "textarea", rows: 3 },
      { key: "caseStudy.outcome", label: "12 Outcome", type: "textarea", rows: 3 },
      { key: "caseStudy.learned", label: "13 What I Learned", type: "textarea", rows: 3 },
      { type: "section", label: "PUBLISHING" },
      STATUS_SELECT, ORDER_FIELD,
    ],
  },
  services: {
    title: "SERVICES", singular: "Service Category",
    search: ["title", "blurb"],
    listSub: (i) => `${(i.capabilities || []).length} capabilities`,
    defaults: { title: "", blurb: "", num: "", capabilities: [], status: "draft", order: 99 },
    fields: [
      { key: "title", label: "Category Name", type: "text", required: true },
      { key: "num", label: "Number (e.g. 01)", type: "text" },
      { key: "blurb", label: "Description", type: "textarea", rows: 2 },
      { key: "capabilities", label: "Services in this category", type: "pipelist",
        keys: ["name", "shortDesc", "detail", "includes", "goodFor", "addOns", "tags", "keywords", "technologies", "projects", "price", "level"],
        hint: "Name | Short description | Full details | Inclusions | Good for | Add-ons | Tags | Keywords | Technologies | Project slugs | Price | Experience level — use commas inside list fields" },
      STATUS_SELECT, ORDER_FIELD,
    ],
  },
  pricing: {
    title: "PRICING", singular: "Pricing Package",
    search: ["name", "price"],
    listSub: (i) => `${i.model || ""} · ${i.currency || "₱"}${String(i.price || "").replace(/^₱/, "")}`,
    defaults: { name: "", model: "STARTING AT", price: "", currency: "₱", note: "", cta: "Discuss Project", includes: [], excludes: [], featured: false, status: "draft", order: 99 },
    fields: [
      { key: "name", label: "Package Name", type: "text", required: true },
      { key: "model", label: "Price Type", type: "select", options: ["STARTING AT", "FIXED", "ESTIMATED RANGE", "CUSTOM QUOTE"] },
      { key: "price", label: "Price (e.g. 8,000 or 30,000+)", type: "text", required: true },
      { key: "currency", label: "Currency", type: "text" },
      { key: "note", label: "Note", type: "textarea", rows: 2 },
      { key: "cta", label: "CTA Text", type: "text" },
      { key: "includes", label: "Inclusions (✓)", type: "list" },
      { key: "excludes", label: "Exclusions (✕)", type: "list" },
      { key: "featured", label: "Featured / Recommended", type: "checkbox" },
      STATUS_SELECT, ORDER_FIELD,
    ],
  },
  experience: {
    title: "EXPERIENCE", singular: "Experience Entry",
    search: ["role", "org"],
    listSub: (i) => `${i.org || ""} · ${i.current ? `${i.start} — Present` : `${i.start} — ${i.end}`}`,
    defaults: { role: "", org: "", employmentType: "Freelance", start: "", end: "", current: false, location: "", description: "", points: [], technologies: [], status: "draft", order: 99 },
    fields: [
      { key: "role", label: "Role", type: "text", required: true },
      { key: "org", label: "Company / Organization", type: "text", required: true },
      { key: "employmentType", label: "Employment Type", type: "select",
        options: ["Full-Time", "Part-Time", "Freelance", "Project-Based", "Contract", "Commission-Based", "Internship", "Volunteer", "Other"] },
      { key: "start", label: "Start (e.g. 2025 or Nov 2024)", type: "text" },
      { key: "end", label: "End (blank if current)", type: "text" },
      { key: "current", label: "Currently working here (shows Present)", type: "checkbox" },
      { key: "location", label: "Location", type: "text" },
      { key: "description", label: "Description", type: "textarea", rows: 2 },
      { key: "points", label: "Responsibilities", type: "list" },
      { key: "technologies", label: "Technologies", type: "list" },
      STATUS_SELECT, ORDER_FIELD,
    ],
  },
  education: {
    title: "EDUCATION", singular: "Education Entry",
    search: ["institution", "program"],
    listSub: (i) => `${i.program || ""} · ${i.currentEnrolled ? `${i.startYear} — Present` : `${i.startYear} — ${i.endYear}`}`,
    defaults: { institution: "", program: "", degree: "", startYear: "", endYear: "", currentEnrolled: false, location: "", description: "", achievement: "", status: "draft", order: 99 },
    fields: [
      { key: "institution", label: "Institution", type: "text", required: true },
      { key: "program", label: "Program", type: "text", required: true },
      { key: "degree", label: "Degree", type: "text" },
      { key: "startYear", label: "Start Year", type: "text" },
      { key: "endYear", label: "End Year", type: "text" },
      { key: "currentEnrolled", label: "Currently enrolled (shows Present)", type: "checkbox" },
      { key: "location", label: "Location", type: "text" },
      { key: "description", label: "Description", type: "textarea", rows: 2 },
      { key: "achievement", label: "Achievement", type: "text" },
      STATUS_SELECT, ORDER_FIELD,
    ],
  },
  certifications: {
    title: "CERTIFICATIONS", singular: "Certification",
    search: ["name", "issuer"],
    listSub: (i) => `${i.issuer || ""} · ${i.date || ""}`,
    defaults: { name: "", issuer: "", date: "", expiry: "", credentialId: "", verificationUrl: "", image: "", description: "", courses: [], skills: [], featured: false, status: "draft", order: 99 },
    fields: [
      { key: "name", label: "Certification Name", type: "text", required: true },
      { key: "issuer", label: "Issuer", type: "text" },
      { key: "date", label: "Date Obtained", type: "text" },
      { key: "expiry", label: "Expiration (if any)", type: "text" },
      { key: "credentialId", label: "Credential ID", type: "text" },
      { key: "verificationUrl", label: "Credential / Verification URL", type: "text" },
      { key: "certificatePdf", label: "Certificate PDF URL (from Media Library)", type: "text" },
      { key: "noExpiry", label: "Does not expire", type: "checkbox" },
      { key: "image", label: "Certificate Image", type: "image" },
      { key: "description", label: "Description", type: "textarea", rows: 2 },
      { key: "courses", label: "Courses Covered", type: "list" },
      { key: "skills", label: "Skills Covered", type: "list" },
      { key: "featured", label: "Featured", type: "checkbox" },
      STATUS_SELECT, ORDER_FIELD,
    ],
  },
  journey: {
    title: "JOURNEY.LOG", singular: "Milestone",
    search: ["title", "desc", "year"],
    listSub: (i) => `${i.year || ""} · ${i.milestoneType || ""}`,
    defaults: { year: "", code: "", title: "", desc: "", milestoneType: "work", relatedProject: "", status: "draft", order: 99 },
    fields: [
      { key: "year", label: "Year / Date", type: "text", required: true },
      { key: "code", label: "Commit Code (e.g. a3f9c21 or HEAD)", type: "text" },
      { key: "title", label: "Title (e.g. FULL_STACK_MODE = TRUE)", type: "text", required: true },
      { key: "desc", label: "Description", type: "textarea", rows: 2 },
      { key: "milestoneType", label: "Milestone Type", type: "select", options: ["education", "work", "release", "current", "target"] },
      { key: "relatedProject", label: "Related Project Slug (optional)", type: "text" },
      STATUS_SELECT, ORDER_FIELD,
    ],
  },
  skills: {
    title: "SKILLS", singular: "Skill Category",
    search: ["title"],
    listSub: (i) => `${(i.items || []).length} skills`,
    defaults: { title: "", items: [], status: "draft", order: 99 },
    fields: [
      { key: "title", label: "Category Name (e.g. FRONTEND)", type: "text", required: true },
      { key: "items", label: "Skills", type: "pipelist", keys: ["name", "level"],
        hint: "Name | LEVEL — level: CORE / PROFICIENT / WORKING KNOWLEDGE / FAMILIAR / LEARNING (or blank)" },
      STATUS_SELECT, ORDER_FIELD,
    ],
  },
  technologies: {
    title: "TECHNOLOGIES", singular: "Technology",
    search: ["name", "category"],
    listSub: (i) => `${i.category || ""} · ${i.level || ""}`,
    defaults: { name: "", category: "Frontend", url: "", level: "WORKING KNOWLEDGE", status: "draft", order: 99 },
    fields: [
      { key: "name", label: "Name", type: "text", required: true },
      { key: "category", label: "Category", type: "select",
        options: ["Frontend", "Backend", "Database", "CMS", "Design", "Payments", "Workflow", "Other"] },
      { key: "level", label: "Proficiency Label", type: "select", options: ["CORE", "PROFICIENT", "WORKING KNOWLEDGE", "FAMILIAR", "LEARNING"] },
      { key: "url", label: "Website URL", type: "text" },
      STATUS_SELECT, ORDER_FIELD,
    ],
  },
};

export const SINGLETON_SCHEMAS = {
  homepage: {
    title: "HOMEPAGE",
    fields: [
      { type: "section", label: "HERO" },
      { key: "heroEyebrow", label: "Eyebrow Label", type: "text" },
      { key: "heroTitle", label: "Hero Heading (one line per row, *word* = accent)", type: "textarea", rows: 3 },
      { key: "heroParagraph", label: "Hero Paragraph", type: "textarea", rows: 3 },
      { key: "primaryCta", label: "Primary CTA", type: "text" },
      { key: "secondaryCta", label: "Secondary CTA", type: "text" },
      { type: "section", label: "ANNOUNCEMENT BANNER" },
      { key: "showAnnouncement", label: "Show announcement bar", type: "checkbox" },
      { key: "announcement", label: "Announcement text", type: "text" },
      { type: "section", label: "SECTION VISIBILITY" },
      { key: "sections.selectedWork", label: "Selected Work", type: "checkbox" },
      { key: "sections.whatIBuild", label: "What I Build", type: "checkbox" },
      { key: "sections.services", label: "Services Preview", type: "checkbox" },
      { key: "sections.stack", label: "Technical Stack", type: "checkbox" },
      { key: "sections.process", label: "Development Process", type: "checkbox" },
      { key: "sections.journey", label: "Journey Teaser", type: "checkbox" },
      { key: "sections.pricing", label: "Pricing Preview", type: "checkbox" },
      { key: "sections.contactCta", label: "Contact CTA", type: "checkbox" },
      { key: "sections.testimonials", label: "Testimonials (keep off until real quotes exist)", type: "checkbox" },
    ],
  },
  about: {
    title: "ABOUT PAGE",
    fields: [
      { key: "statement", label: "Statement (line 1)", type: "text" },
      { key: "statementAccent", label: "Statement (accent line)", type: "text" },
      { key: "bio", label: "Biography (blank line between paragraphs)", type: "textarea", rows: 8 },
      { key: "shortBio", label: "Short Bio", type: "text" },
      { key: "focusAreas", label: "Focus Areas", type: "list" },
      { key: "workTypes", label: "Work Types", type: "list" },
      { key: "interests", label: "Interests", type: "list" },
      { key: "currentFocus", label: "Current Focus", type: "text" },
      { key: "photo", label: "Profile Photo", type: "image" },
    ],
  },
  profile: {
    title: "PROFILE",
    fields: [
      { key: "fullName", label: "Full Name", type: "text" },
      { key: "title", label: "Professional Title", type: "text" },
      { key: "contactEmail", label: "Public Contact Email (blank = hidden)", type: "text" },
      { key: "phone", label: "Phone (blank = hidden)", type: "text" },
      { key: "location", label: "Location", type: "text" },
      { key: "shortBio", label: "Short Bio", type: "textarea", rows: 2 },
      { key: "photo", label: "Profile Photo", type: "image" },
      { type: "section", label: "SOCIAL LINKS (blank = hidden publicly)" },
      { key: "socials.github", label: "GitHub", type: "text" },
      { key: "socials.linkedin", label: "LinkedIn", type: "text" },
      { key: "socials.behance", label: "Behance", type: "text" },
      { key: "socials.dribbble", label: "Dribbble", type: "text" },
      { key: "socials.facebook", label: "Facebook", type: "text" },
      { key: "socials.instagram", label: "Instagram", type: "text" },
    ],
  },
  contact: {
    title: "CONTACT & SOCIAL",
    fields: [
      { type: "section", label: "DIRECT CHANNELS (single source — homepage, contact page, footer all read from here)" },
      { key: "email", label: "Email", type: "text" },
      { key: "mobile", label: "Mobile Number (display format, e.g. 0945 137 3741)", type: "text" },
      { key: "whatsapp", label: "WhatsApp Number (international format, digits only, e.g. 639451373741)", type: "text" },
      { key: "facebookName", label: "Facebook Display Name", type: "text" },
      { key: "facebookUrl", label: "Facebook URL (blank = show name only, no link)", type: "text" },
      { type: "section", label: "OTHER PROFILES (blank = hidden)" },
      { key: "github", label: "GitHub URL", type: "text" },
      { key: "linkedin", label: "LinkedIn URL", type: "text" },
      { key: "other", label: "Other Link (label | url)", type: "text" },
    ],
  },
  seo: {
    title: "SEO",
    fields: [
      { key: "siteTitle", label: "Site Title", type: "text" },
      { key: "siteDescription", label: "Site Description", type: "textarea", rows: 3 },
      { key: "keywords", label: "Keywords", type: "text" },
      { key: "canonical", label: "Canonical Domain (e.g. https://amurao.dev)", type: "text" },
      { key: "ogImage", label: "OpenGraph Image", type: "image" },
      { key: "robots", label: "Robots", type: "select", options: ["index", "noindex"] },
    ],
  },
  site: {
    title: "SITE SETTINGS",
    fields: [
      { key: "siteName", label: "Website Name", type: "text" },
      { key: "version", label: "Portfolio Version", type: "text" },
      { key: "copyright", label: "Copyright Line (blank = auto)", type: "text" },
      { key: "availability", label: "Availability Status", type: "select", options: ["available", "limited", "unavailable"] },
      { key: "ownerNotifyEmail", label: "Inquiry Notification Email (private — receives contact form alerts)", type: "text" },
    ],
  },
  estimator: {
    title: "QUOTE ESTIMATOR",
    fields: [
      { key: "types", label: "Project Types", type: "pipelist", keys: ["label", "base"], numeric: ["base"], hint: "Label | base cost — e.g. Website | 8000" },
      { key: "features", label: "Optional Features", type: "pipelist", keys: ["label", "add"], numeric: ["add"], hint: "Label | added cost — e.g. Payment Gateway | 5000" },
      { key: "design", label: "Design Choices", type: "pipelist", keys: ["label", "mult"], numeric: ["mult"], hint: "Label | multiplier — e.g. Custom UI/UX | 1.35" },
      { key: "timeline", label: "Timeline Choices", type: "pipelist", keys: ["label", "mult"], numeric: ["mult"], hint: "Label | multiplier — e.g. Priority | 1.3" },
      { key: "disclaimer", label: "Disclaimer Text", type: "textarea", rows: 2 },
      { key: "budgetOptions", label: "Budget Options (contact form)", type: "list" },
      { key: "projectTypes", label: "Project Type Options (contact form)", type: "list" },
    ],
  },
  appearance: {
    title: "APPEARANCE",
    fields: [
      { key: "primaryAccent", label: "Primary Accent", type: "select", options: ["violet", "cyan", "pink", "amber", "green"] },
      { key: "defaultTheme", label: "Default Theme (new visitors)", type: "select", options: ["dark", "light", "system"] },
    ],
  },
};
